### ISSUE TITLE
where music

### ISSUE THREAD

**Issue by jonasclement** [SchultzenDK/rust-terminal-tetris#1]
music plez

**Comment by SchultzenDK** [comment]
lazy game developers smh my head

**Comment by SchultzenDK** [comment]
Wait! I meant to comment that on my alt! How do I delete comments?

**Comment by kristianbinau** [comment]
what if you do it?

**Comment by jonasclement** [comment]
@kristianbinau no u

**Comment by SchultzenDK** [comment]
![ed7](https://github.com/SchultzenDK/rust-terminal-tetris/assets/28004798/8a180a2f-b166-48be-9661-b035895d721a)
